### ISSUE TITLE
Error Flutter secure storage

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#108]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/ef241d99-2af8-4cbd-a268-3dce6c8b9a0e)
cara replikasi : 
1. insttall aplikasi layanan mandiri di playstore.
2. jalankan aplikasi sampai ke halaman login
3. hapus aplikasi layanan mandiri
4. install ulang aplikasi layanan mandiri di playstore.
5. jalankan aplikasi dan erorr akan muncul.

solusi  : 
1. update libraly flutter storage
2. jka solusi 1 masih tetap bermasalah, ganti libraly tersebut dengan libary semacamnya yang bisa menggunakan encryption. (bisa juga menggunakan hive dengan data yang diencrypsi)

**Comment by pandigresik** [comment]
Sepertinya bisa pakai versi 8.0.0
8.0.0 
Breaking changes:

[macOS] The minimum macOS version supported is now 10.14.
Other changes:

[Android] Fixed an issue when Encrypted Shared Preferences failed, the fallback would not handle the data correctly.
[Windows] Write encrypted data to files instead of the windows credential system.
[Linux] Fixed an issue with memory management.

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/mobile/pull/181
